version: '3.8'

services:
  greenplum:
    # Используем проверенный образ для обучения (gpadmin,no password)
    # image: sergeyosechkin/greenplum:latest
    image: pro100filipp/greenplum-with-pxf:latest
    container_name: greenplum
    ports:
      - "5433:5432" # Порт мастера для подключения через DBeaver/psql
      - "2222:22"   # SSH, если захочешь зайти внутрь "как на сервер"
      - "5888:5888" # Порт для PXF
    environment:
      - GPDATA_NUM_PRIMARY_SEGMENTS=2 # 2 сегмента = 2 шарда на одном ноуте
      - GP_PASSWORD=123456
    shm_size: '2gb' # Важно! Интерконнект активно использует общую память
    volumes:
      # Пробрасываем папку для данных, чтобы они не пропадали
      - ./gpdata/segments:/srv/gpdata
      - ./gpdata/master:/srv/gpmaster
    deploy:
      resources:
        limits:
          memory: 4gb # Ограничиваем аппетит GP, чтобы VMware не зависла
